### ISSUE TITLE
브라우저 종료 시 스크립트는 종료되지 않음

### ISSUE THREAD

**Issue by joonas-yoon** [joonas-yoon/boj-source-downloader#1]
브라우저 종료 시 스크립트는 종료되지 않음

**Comment by joonas-yoon** [comment]
`pyinstaller`로 exe 파일을 만들어서 사용할 경우, 아래와 같은 오류로 커맨드창은 종료가 안 된다:
```
DevTools listening on ws://127.0.0.1:10139/devtools/browser/91b084d9-f0fb-4558-b7e6-04eb11b10cc1

KLIB_SelfTest return : KLR_OK

Traceback (most recent call last):
  File "main.py", line 23, in <module>
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 679, in page_source
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=80.0.3987.163)

[15248] Failed to execute script main
```

pyinstaller 패키지의 문제인지 확인 필요
